easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            controller: App\Controller\ArticleController
            list:
                max_results: 40
                title: "Stock"
                fields: 
                    - { property: 'nom', label: 'Désignation'}
                    - { property: 'pn', label: 'Pn'}
                    - { property: 'last_prix', label: 'Prix Ht (€)', css_class: 'text-right'}
                    - { property: 'marge', label: 'Marge (%)', css_class: 'text-right' }
                    - { property: 'quantite', label: 'Quantité', css_class: 'text-right'}
                    - { property: 'seuil_alert', label: "Seuil d'alerte", css_class: 'text-right'}
                actions:
                    - { name: 'addFormone', icon: 'plus-circle', label: "FormOne" }
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'times', label: false }
            show:
                title: "Stock"
                fields: 
                    - { property: 'nom', label: "Désignation", css_class: 'col-sm-6'}
                    - { property: 'pn', label: 'Pn', css_class: 'col-sm-6'}
                    - { property: 'last_prix', label: "Prix Ht (€)", css_class: 'col-sm-6'}
                    - { property: 'marge', label: "Marge (%)", css_class: 'col-sm-6'}
                    - { property: 'quantite', label: "Quantité total", css_class: 'col-sm-6'}
                    - { property: 'seuil_alert', label: "Seuil d'alerte", css_class: 'col-sm-6'}
                    - { property: 'article_formone', label: 'Form one', css_class: 'new-row col-sm-6', template: 'list_formone.html.twig'}
                    - { property: 'article_prix', label: 'Historique des prix', css_class: 'col-sm-6', template: 'list_article_prix.html.twig'}
                actions:
                    - { name: 'addFormone', icon: 'plus-circle', label: "FormOne", css_class: 'btn btn-secondary' }   
            form:
                title: "Ajouter un article au stock"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '', background: 'box-primary' }
                    - { property: 'pn', label: 'Pn', css_class: 'col-sm-6'}
                    - { property: 'nom', label: 'Désignation', css_class: 'col-sm-6'}
                    - { property: 'prix_ht', label: 'Prix HT', type: 'text', type_options: { required: true }, css_class: 'col-sm-6'}
                    - { property: 'marge', label: 'Marge', css_class: 'col-sm-6'}
                    - { property: 'seuil_alert', label: "Seuil d'alerte", type_options: { attr: {min: '0' }}, css_class: 'col-sm-6'}
            edit:
                title: "Modifier un article du stock"