easy_admin:
    entities:
        ArticleMarge:
            class: App\Entity\ArticleMarge
            disabled_actions: ['delete']

            form:
                fields:
                    - { property: 'marge', label: 'Marge', css_class: 'col-sm-6'}
                    - { property: 'article', label: 'Article', css_class: 'col-sm-6'}