easy_admin:
    entities:
        Client:
            class: App\Entity\Client
            disabled_actions: ['show']
            list:
                role: ROLE_SUPER_ADMIN
                title: "Clients"
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Modifier', css_class: 'btn btn-secondary' }
                    - { name: 'delete', icon: 'times', label: 'Supprimer', css_class: 'btn btn-secondary text-danger' }       
            form:
                role: ROLE_SUPER_ADMIN
                title: "Ajouter un client"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '', background: 'box-purple' }
                    - { property: 'nom', label: 'Nom', css_class: 'col-sm-3'}
                    - { property: 'prenom', label: 'Prénom', css_class: 'col-sm-3'}
                    - { property: 'entreprise', label: 'Entreprise', css_class: 'col-sm-6'}
                    - { property: 'email', label: 'Email', css_class: 'col-sm-6'}
                    - { property: 'tel', label: 'Téléphone', css_class: 'col-sm-6'}
                    - { property: 'adresse', label: 'Adresse', css_class: 'col-sm-6'}
                    - { property: 'cp', label: 'Code postal', css_class: 'col-sm-2'}
                    - { property: 'ville', label: 'Ville', css_class: 'col-sm-4'}
                    
            edit:
                role: ROLE_SUPER_ADMIN
                title: "Modifier un client"
            show:
                role: ROLE_SUPER_ADMIN
            new:
                role: ROLE_SUPER_ADMIN
            delete:
                role: ROLE_SUPER_ADMIN