parameters:
   statut_dossier: {'0':'En cours', '1':'Terminé'}

easy_admin:
    entities:
        Dossier:
            class: App\Entity\Dossier
            controller: App\Controller\DossierController
            show:
                actions:
                    #- { name: 'dossier_cri', type: 'route', icon: 'eye', label: "CRI", css_class: 'btn btn-info' }
                    #- { name: 'dossier_crs', type: 'route', icon: 'eye', label: "CRS", css_class: 'btn btn-info' }
                    #- { name: 'dossier_aprs', type: 'route', icon: 'eye', label: "APRS", css_class: 'btn btn-info' }
                    - { name: 'aprs', icon: 'eye', label: "APRS", css_class: 'btn btn-secondary', target: '_blank' }
                    - { name: 'getDossier', icon: 'print', label: "Dossier", css_class: 'btn btn-secondary', target: '_blank' }
                    - { name: 'generate', icon: 'refresh', label: "Regénérer", css_class: 'btn btn-warning' }
                    - { name: 'cloturer', icon: 'check', label: "Cloturer", css_class: 'btn btn-danger' }
                    #- { name: 'validate', icon: 'check', label: "Cloturer le dossier", css_class: 'btn btn-danger' }
            list:
                title: "Dossiers"
                #dql_filter: 'entity.statut = 1'
                fields: 
                    - { property: 'num_bl', label: 'N° dossier'}
                    - { property: 'titre', label: 'Titre'}
                    - { property: 'num_bc', label: 'N° de bon de commande'}
                    - { property: 'date_creation', label: 'Date de création', format: 'd/m/Y'}
                    - { property: 'appareil', label: 'Appareil'}
                    - { property: 'statut', label: "Statut", template: 'statut_list.html.twig', statut: '%statut_dossier%'}
            search:
                fields:
                    - { property: 'num_bl'}       
                    - { property: 'titre'}       
                    - { property: 'num_bc'}       
                    - { property: 'date_creation'}       
                    - { property: 'appareil', searchField: ['immatriculation']}       
            form:
                title: "Ajouter un dossier"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations générales', background: 'box-success' }
                    - { property: 'appareil', label: "Appareil", css_class: 'col-sm-6'}
                    - { property: 'titre', label: "Titre du dossier", css_class: 'col-sm-6'}
                    - { property: 'num_bc', label: "N° de bon de Commande", css_class: 'col-sm-6'}
                    - { property: 'scanBcFile', label: 'Scan du bon de commande', type: 'vich_file', type_options: {allow_delete: false}, css_class: 'col-sm-6'}
                    - { property: 'heure_derniere_aprs', label: 'Heures depuis dernière APRS', type: 'text', css_class: 'col-sm-6 new-row'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Travaux demandés :', background: 'box-warning' }
                    - { property: 'travaux', label: false, type: 'collection', type_options: { entry_type: 'App\Form\DossierTravauxType', mapped: true, allow_add: true, required: false, allow_delete: true, by_reference: false, entry_options: {label: false} }, css_class: 'col-sm-12'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'CN / AD :', background: 'box-warning' }
                    - { property: 'cnad', label: false, type: 'collection', type_options: { entry_type: 'App\Form\DossierCnadType', mapped: true, allow_add: true, required: false, allow_delete: true, by_reference: false, entry_options: {label: false} }, css_class: 'col-sm-12'}
            edit:
                title: "Modifier un dossier"
            delete:
                role: ROLE_SUPER_ADMIN
