easy_admin:
    entities:
        DossierMainOeuvre:
            class: App\Entity\DossierMainOeuvre
            controller: App\Controller\DossierMainOeuvreController
            form:
                title: "Ajouter une main d'oeuvre"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '', background: 'box-danger' }
                    - { property: 'date_realisation', label: "Date", type_options: { widget: 'single_text' }, css_class: 'col-sm-3'}
                    - { property: 'main_oeuvre', label: "Main d'oeuvre", css_class: 'col-sm-6'}
                    - { property: 'quantite', label: "Quantité", css_class: 'col-sm-3'}
            edit:
                title: "Modifier une main d'oeuvre"
                fields:
                    - { property: 'date_realisation', label: "Date", type_options: { widget: 'single_text' }, css_class: 'col-sm-3'}
                    - { property: 'main_oeuvre', label: "Main d'oeuvre", type_options: { disabled: true }, css_class: 'col-sm-6'}
                    - { property: 'quantite', label: "Quantité", css_class: 'col-sm-3'}
