easy_admin:
    entities:
        DossierArticle:
            class: App\Entity\DossierArticle
            controller: App\Controller\DossierArticleController
            form:
                title: "Ajouter un article"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '', background: 'box-danger' }
                    - { property: 'article_formone', label: "Article", type_options: { query_builder: 'App\Repository\ArticleFormoneRepository::getListQuantityNotNull'}, css_class: 'col-sm-9'}
                    - { property: 'quantite', label: "Quantité", css_class: 'col-sm-3'}
            edit:
                title: "Modifier un article"
                fields:
                    - { property: 'article_formone', label: "Article", type_options: { disabled: true }, css_class: 'col-sm-9'}
                    - { property: 'quantite', label: "Quantité", css_class: 'col-sm-3'}

