easy_admin:
    entities:
        Mecanicien:
            class: App\Entity\Mecanicien
            image_base_path: '%app.path.signature_images%'
            #disabled_actions: ['delete']
            disabled_actions: ['show']
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary text-white' }
                    - { name: 'delete', icon: 'times', label: false, css_class: 'btn btn-secondary text-danger ' }
                title: "Mécaniciens"
            form:
                title: "Ajouter un mécanicien"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '' }
                    - { property: 'nom', label: 'Nom', css_class: 'col-sm-6'}
                    - { property: 'prenom', label: 'Prénom', css_class: 'col-sm-6'}
                    - { property: 'licence', label: 'Licence', css_class: 'col-sm-6'}
                    - { property: 'signatureFile', label: 'Signature', type: 'vich_image', type_options: {allow_delete: false}, css_class: 'col-sm-6'}
            edit:
                title: "Modifier un mécanicien"
