parameters:
   type_outillage: {'Outillage standard':'0', 'Compression':'1'}

easy_admin:
    entities:
        Outillage:
            class: App\Entity\Outillage
            controller: App\Controller\OutillageController
            disabled_actions: ['show']
            list:
                role: ROLE_SUPER_ADMIN
                title: "Outillages"
                actions:
                    - { name: 'addCertificat', icon: 'plus-circle', label: "Certificat", css_class: 'btn btn-secondary ' }
                    - { name: 'edit', icon: 'pencil', label: 'Modifier', css_class: 'btn btn-secondary ' }
                    - { name: 'delete', icon: 'times', label: 'Supprimer', css_class: 'btn btn-secondary text-danger' }
                fields: 
                    - { property: 'nom', label: 'Nom'}
                    - { property: 'sn', label: 'Sn'}
                    - { property: 'pn', label: 'Pn'}
                    - { property: 'last_date_certificat', label: 'Date de validité', template: 'last_certificat.html.twig'}

            show:
                role: ROLE_SUPER_ADMIN
                actions:
                    - { name: 'addCertificat', icon: 'plus-circle', label: "certificat", css_class: 'btn btn-secondary' }
                fields: 
                    - { property: 'nom', label: 'Nom', css_class: 'col-sm-6'}
                    - { property: 'type', label: "Type d'outillage", css_class: 'col-sm-6', template: 'outillage_type.html.twig', type_outillage: '%type_outillage%'}
                    - { property: 'sn', label: "Sn", css_class: 'col-sm-6'}
                    - { property: 'pn', label: "Pn", css_class: 'col-sm-6'}
                    - { property: 'outillage_certificats', label: 'Date de validité', css_class: 'col-sm-6', template: 'list_certificat.html.twig'}
            form:
                role: ROLE_SUPER_ADMIN
                title: "Ajouter un outillage"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '', background: 'box-primary' }
                    - { property: 'nom', label: 'Nom', css_class: 'col-sm-6'}
                    - { property: 'type', label: "Type d'outillage", type: 'choice', type_options: {choices: '%type_outillage%', expanded: false, multiple: false }, css_class: 'col-sm-6'}
                    - { property: 'sn', label: 'Sn', css_class: 'col-sm-6'}
                    - { property: 'pn', label: 'Pn', css_class: 'col-sm-6'}
                    - { property: 'prix_ht', label: 'Prix HT', type: 'text', type_options: { required: true }, css_class: 'col-sm-6'}
            edit:
                role: ROLE_SUPER_ADMIN
                title: "Modifier un outillage"
            new:
                role: ROLE_SUPER_ADMIN
            delete:
                role: ROLE_SUPER_ADMIN