easy_admin:
    entities:
        ProgrammeEntretien:
            class: App\Entity\ProgrammeEntretien
            controller: App\Controller\ProgrammeEntretienController
            form:
                title: "Ajouter un programme d'entretien"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: '', background: 'box-warning' }
                    - { property: 'type', label: 'Type', css_class: 'col-sm-6'}
                    - { property: 'edition', label: 'Edition', css_class: 'col-sm-6'}
                    - { property: 'revision', label: 'Révision / Acceptation', css_class: 'col-sm-6'}
                    - { property: 'date', label: 'Date du PE', type_options: { widget: 'single_text' }, css_class: 'col-sm-6' }
            edit:
                title: "Modifier un programme d'entretien"
