easy_admin:
    entities:
        Todo:
            class: App\Entity\Todo
            controller: App\Controller\TodoController
            list:
                role: ROLE_SUPER_ADMIN
                title: "Notes"
                fields: 
                    - { property: 'titre', label: 'Titre'}
                    - { property: 'note', label: 'Note'}
                    - { property: 'date_creation', label: 'Date de création', format: 'd/m/Y'}
                    - { property: 'date_modif', label: 'Dernière modification', format: 'd/m/Y'}
                    - { property: 'client', label: 'Client'}
                    - { property: 'appareil', label: 'Appareil'}
                actions:
                    - { name: 'new', label: 'Créer une note' }
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'times', label: false }
            show:
                role: ROLE_SUPER_ADMIN
                title: "Notes"
                fields: 
                    - { property: 'titre', label: 'Titre', css_class: 'col-sm-6'}
                    - { property: 'note', label: 'Note', css_class: 'col-sm-6'}
                    - { property: 'client', label: 'Client', css_class: 'col-sm-6'}
                    - { property: 'appareil', label: 'Appareil', css_class: 'col-sm-6'}
            form:
                role: ROLE_SUPER_ADMIN
                title: "Ajouter une note"
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations générales' }
                    - { property: 'titre', label: 'Titre', css_class: 'col-sm-12'}
                    - { property: 'note', label: 'Note', css_class: 'col-sm-12'}
                    - { type: 'group', css_class: 'col-sm-12', label: 'Liens (Optionel)' }
                    - { property: 'client', label: 'Client', css_class: 'col-sm-6'}
                    - { property: 'appareil', label: 'Appareil', css_class: 'col-sm-6'}
            edit:
                role: ROLE_SUPER_ADMIN
                title: "Modifier une note"
            new:
                role: ROLE_SUPER_ADMIN
            delete:
                role: ROLE_SUPER_ADMIN